### ISSUE TITLE
Getting error: EndOfStreamException was Unhandled

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SourceCodeDude/n-battle-net-api#1]
```
Here is my code in a button click event with a textbox on a form:


        private void button1_Click(object sender, EventArgs e)
        {

            using (BattleNetClient client = new BattleNetClient(BattleNet.API.WoW.Region.US))
            {
                Character c = client.GetCharacter("Cho'gall", "Healkin");
                textBox1.Text += c.Name;



            }

        }


Here is a screenshot of the Error: http://puu.sh/3Md4
```

Original issue reported on code.google.com by `kdun...@gmail.com` on 28 Jul 2011 at 9:31

**Comment by GoogleCodeExporter** [comment]
```
Here is the stack trace:


System.IO.EndOfStreamException was unhandled
  Message=Unable to read beyond the end of the stream.
  Source=mscorlib
  StackTrace:
       at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
       at System.IO.BinaryReader.ReadInt64()
       at BattleNet.API.CacheItem.Create(Stream st, Cache c)
       at BattleNet.API.Cache.Prime()
       at BattleNet.API.Cache..ctor(String storePath)
       at BattleNet.API.WoW.BattleNetClient..ctor(Region r, CultureInfo loc)
       at BattleNet.API.WoW.BattleNetClient..ctor(Region r)
       at BlizzAPITester.Form1.button1_Click(Object sender, EventArgs e) in C:\Users\kdunlap\documents\visual studio 2010\Projects\BlizzAPITester\BlizzAPITester\Form1.cs:line 23
       at System.Windows.Forms.Control.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ButtonBase.WndProc(Message& m)
       at System.Windows.Forms.Button.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at BlizzAPITester.Program.Main() in c:\users\kdunlap\documents\visual studio 2010\Projects\BlizzAPITester\BlizzAPITester\Program.cs:line 18
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

Original comment by `kdun...@gmail.com` on 28 Jul 2011 at 9:43

**Comment by GoogleCodeExporter** [comment]
```
This issue is resolved. I just deleted the cache folder and it works fine now.
```

Original comment by `kdun...@gmail.com` on 29 Jul 2011 at 7:16

**Comment by GoogleCodeExporter** [comment]
```
I'll have to add a check for that in the next release.  Thanks for the feedback
```

Original comment by `shimmanning@gmail.com` on 1 Aug 2011 at 2:46

**Comment by GoogleCodeExporter** [comment]
```
I believe the problem was caused by having an older version of the cache.  
Rev 18 e0f0c17fa6b6 has a fix for this and will delete the cache if it 
encounters and unknown version.
```

Original comment by `shimmanning@gmail.com` on 2 Aug 2011 at 2:02
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `shimmanning@gmail.com` on 12 Aug 2011 at 1:50
- Changed state: **Verified**
