### ISSUE TITLE
PrivateKey Errors

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SourceCodeDude/n-battle-net-api#2]
```
When setting the PrivateKey there is a FormatException:

System.FormatException was unhandled
  Message=Additional non-parsable characters are at the end of the string.
  Source=mscorlib
  StackTrace:
       at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
       at System.Convert.ToByte(String value, Int32 fromBase)
       at BattleNet.API.WoW.BattleNetClient.set_PrivateKey(String value)


This is in the latest version. Blizzard's API keys are alpha-numeric. The 
public key seems to work without a problem.

```

Original issue reported on code.google.com by `trice.sc...@gmail.com` on 3 Aug 2011 at 11:56

**Comment by GoogleCodeExporter** [comment]
```
Feel free to contact me for more information.
```

Original comment by `trice.sc...@gmail.com` on 3 Aug 2011 at 11:57

**Comment by GoogleCodeExporter** [comment]
```
It appears that this is fixed in your latest version in source control.
```

Original comment by `trice.sc...@gmail.com` on 4 Aug 2011 at 12:39

**Comment by GoogleCodeExporter** [comment]
```
You are correct, there are fixes for this in the source control.  Will be 
releasing it soon once I clean up some things.

This issues is because the original documentation made it look like it was a 
hex value so i was parsing it as 2 hex characters.  Turns out it was raw ascii
```

Original comment by `shimmanning@gmail.com` on 5 Aug 2011 at 1:40
- Changed state: **Verified**
